### ISSUE TITLE
How to #include "TcpClient.h" in my project with bazel? 

### ISSUE THREAD

**Issue by hlqqlm** [Edward-Elric233/libhv-bazel-test#1]
My project use libhv with bazel. #include "hloop.h" is ok, but #include "TcpClient.h" failed, I also tried #include "evpp/TcpClient.h".

My prject bazel scripts are:

WORKSPACE:
```
git_repository(
        name = "libhv",
        commit = "a4e51af3ca94eebb311dca2a03514e191d2ca318",
        remote = "https://gitee.com/libhv/libhv",
        )
```

src/BUILD：
```
cc_binary(
        name = "my_project",
        srcs = glob(["*.cc", "*.h"]),
        includes = ["./"],
        deps = [
                "@libhv//:hv",
                ],
        )
```

main.cc：
```
#include "hloop.h"			<--- ok
#include "hsocket.h"		<--- ok
...
#include "TcpClient.h"		<--- failed
#include "evpp/TcpClient.h"	<--- failed

```

**Comment by Edward-Elric233** [comment]
I forgot to mention the need to add .bazelrc in the README before, and it has now been fixed. I have tried to answer this question at https://github.com/ithewei/libhv/issues/529, please see if it helps.
